netty:
  ip: 10.36.137.21
  port: 20000
zk:
  host: 192.168.227.130:2181
spring:
  redis:
    host: 192.168.227.130
    password: root
  rabbitmq:
    host: 192.168.227.130
    username: admin
    password: admin
    virtual-host: /admin